### ISSUE TITLE
Error instantiating GoogleDriveStorage()

### ISSUE THREAD

**Issue by zalokhan** [torre76/django-googledrive-storage#10]
Hi,
I am using this for a project. As mentioned in the docs, I have plaved the p12 file converted it to a human-readable format (finalkey).
In the settings.py file I am passing the file path to the variable 
GOOGLE_DRIVE_STORAGE_KEY = 'finalkey' 
I am getting the following error:
>>> gd_storage = GoogleDriveStorage()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/gdstorage/storage.py", line 55, in __init__
    self._drive_service = build('drive', 'v2', http=http)
  File "/Library/Python/2.7/site-packages/oauth2client/util.py", line 140, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/googleapiclient/discovery.py", line 203, in build
    cache)
  File "/Library/Python/2.7/site-packages/googleapiclient/discovery.py", line 249, in _retrieve_discovery_doc
    resp, content = http.request(actual_url)
  File "/Library/Python/2.7/site-packages/oauth2client/client.py", line 572, in new_request
    self._refresh(request_orig)
  File "/Library/Python/2.7/site-packages/oauth2client/client.py", line 842, in _refresh
    self._do_refresh_request(http_request)
  File "/Library/Python/2.7/site-packages/oauth2client/client.py", line 869, in _do_refresh_request
    body = self._generate_refresh_request_body()
  File "/Library/Python/2.7/site-packages/oauth2client/client.py", line 1549, in _generate_refresh_request_body
    assertion = self._generate_assertion()
  File "/Library/Python/2.7/site-packages/oauth2client/client.py", line 1677, in _generate_assertion
    private_key, self.private_key_password), payload)
  File "/Library/Python/2.7/site-packages/oauth2client/_openssl_crypt.py", line 120, in from_string
    pkey = crypto.load_pkcs12(key, password).get_privatekey()
Error: [('asn1 encoding routines', 'ASN1_D2I_READ_BIO', 'not enough data')]

It would be great if you could help me with this.

**Comment by torre76** [comment]
You should not pass the path to the file, you should pass **the content of the file**.
Something like:

```python
GOOGLE_DRIVE_STORAGE_KEY = file("/path/to/key/file","rb").read()
```
