### ISSUE TITLE
AttributeError: 'str' object has no attribute 'sign'

### ISSUE THREAD

**Issue by rauleb** [torre76/django-googledrive-storage#15]
```
Traceback (most recent call last):
  File "/Users/rauleburro/Documents/Django/infopy/env/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/rauleburro/Documents/Django/infopy/env/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/Users/rauleburro/Documents/Django/infopy/env/lib/python2.7/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/Users/rauleburro/Documents/Django/infopy/env/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/rauleburro/Documents/Django/infopy/env/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/rauleburro/Documents/Django/infopy/env/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/rauleburro/Documents/Django/infopy/env/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/rauleburro/Documents/Django/infopy/core/models.py", line 14, in <module>
    gd = GoogleDriveStorage()
  File "/Users/rauleburro/Documents/Django/infopy/env/lib/python2.7/site-packages/gdstorage/storage.py", line 55, in __init__
    self._drive_service = build('drive', 'v2', http=http)
  File "/Users/rauleburro/Documents/Django/infopy/env/lib/python2.7/site-packages/oauth2client/util.py", line 135, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/rauleburro/Documents/Django/infopy/env/lib/python2.7/site-packages/googleapiclient/discovery.py", line 207, in build
    cache)
  File "/Users/rauleburro/Documents/Django/infopy/env/lib/python2.7/site-packages/googleapiclient/discovery.py", line 254, in _retrieve_discovery_doc
    resp, content = http.request(actual_url)
  File "/Users/rauleburro/Documents/Django/infopy/env/lib/python2.7/site-packages/oauth2client/client.py", line 616, in new_request
    self._refresh(request_orig)
  File "/Users/rauleburro/Documents/Django/infopy/env/lib/python2.7/site-packages/oauth2client/client.py", line 873, in _refresh
    self._do_refresh_request(http_request)
  File "/Users/rauleburro/Documents/Django/infopy/env/lib/python2.7/site-packages/oauth2client/client.py", line 900, in _do_refresh_request
    body = self._generate_refresh_request_body()
  File "/Users/rauleburro/Documents/Django/infopy/env/lib/python2.7/site-packages/oauth2client/client.py", line 1611, in _generate_refresh_request_body
    assertion = self._generate_assertion()
  File "/Users/rauleburro/Documents/Django/infopy/env/lib/python2.7/site-packages/oauth2client/service_account.py", line 396, in _generate_assertion
    key_id=self._private_key_id)
  File "/Users/rauleburro/Documents/Django/infopy/env/lib/python2.7/site-packages/oauth2client/crypt.py", line 97, in make_signed_jwt
    signature = signer.sign(signing_input)
AttributeError: 'str' object has no attribute 'sign'
```

**Comment by torre76** [comment]
Hi @rauleb,

I take a quick look to the problem and it seems that it is related to a [PyOpenSSL missing implementation](https://github.com/google/oauth2client/issues/112).

This is strange because I used [PyCrypto](https://www.dlitz.net/software/pycrypto/) as SSL Layer in my project.

I am supposing that in your project you have also installed PyOpenSSL which interferes with PyCrypto but I need you verify this supposition on your system.

Could you attach the output of  `pip freeze` command to this issue?

Regards
Gian Luca

**Comment by rauleb** [comment]
```
dj-static==0.0.6
Django==1.9.7
django-appconf==1.0.2
django-googledrive-storage==1.1.4
django-password-reset==0.9
djangorestframework==3.3.3
google-api-python-client==1.5.1
gunicorn==19.6.0
httplib2==0.9.2
oauth2client==2.2.0
Pillow==3.2.0
psycopg2==2.6.1
pyasn1==0.1.9
pyasn1-modules==0.0.8
pycrypto==2.6.1
python-dateutil==2.5.3
requests==2.10.0
rsa==3.4.2
simplejson==3.8.2
six==1.10.0
static3==0.7.0
uritemplate==0.6
```

**Comment by torre76** [comment]
Hi @rauleb,

you could use version 1.2.0 which hopefully solves your problems.
Regards.

**Comment by AmanKahlon90** [comment]
@torre76 , Downgrading from python 3.6.5 to  version 2 didnt fix it.

**Comment by AmanKahlon90** [comment]
@rauleb I am having the same issue, did you end up resolving this issue?

Thanks

**Comment by torre76** [comment]
@AmanKahlon90 Which version of DGS are you using?

**Comment by AmanKahlon90** [comment]
@torre76 I did pip freeze and I got the following result:
google-api-python-client==1.6.6
httplib2==0.11.3
oauth2client==4.1.2
pyasn1==0.4.2
pyasn1-modules==0.2.1
rsa==3.4.2
six==1.11.0
uritemplate==3.0.0
And i get the exact same error as above with the following code:
f = open('c:\ExamCreator\My Project-9352ed298182.json') 
key = f.read()
f.close()
credentials = ServiceAccountCredentials('CLIENT_EMAIL', 
key, scope='https://www.googleapis.com/auth/admin.directory.user', sub='examcreator@stately-will-200116.iam.gserviceaccount.com')
http = httplib2.Http()
http = credentials.authorize(http)
userinfo = {'primaryEmail': 'test1@test.grasslands.ab.ca',
					'name': { 'givenName':'John','familyName':'Smith' },
					'password': 'Hello1'}
 service = discovery.build("admin", "directory_v1", http=http) service.users().insert(body=userinfo).execute()
The error is thrown at discovery.build("admin", "directory_v1", http=http) .
Can you provide your feedback on this

**Comment by AmanKahlon90** [comment]
@torre76 I get the following error:
Traceback (most recent call last):
  File "C:\ExamCreator\TestSample.py", line 43, in <module>
    main(sys.argv)
  File "C:\ExamCreator\TestSample.py", line 36, in main
    service = discovery.build("admin", "directory_v1", http=http)
  File "C:\Python\lib\site-packages\oauth2client\_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Python\lib\site-packages\googleapiclient\discovery.py", line 229, in build
    requested_url, discovery_http, cache_discovery, cache)
  File "C:\Python\lib\site-packages\googleapiclient\discovery.py", line 276, in _retrieve_discovery_doc
    resp, content = http.request(actual_url)
  File "C:\Python\lib\site-packages\oauth2client\transport.py", line 159, in new_request
    credentials._refresh(orig_request_method)
  File "C:\Python\lib\site-packages\oauth2client\client.py", line 749, in _refresh
    self._do_refresh_request(http)
  File "C:\Python\lib\site-packages\oauth2client\client.py", line 774, in _do_refresh_request
    body = self._generate_refresh_request_body()
  File "C:\Python\lib\site-packages\oauth2client\client.py", line 1484, in _generate_refresh_request_body
    assertion = self._generate_assertion()
  File "C:\Python\lib\site-packages\oauth2client\service_account.py", line 385, in _generate_assertion
    key_id=self._private_key_id)
  File "C:\Python\lib\site-packages\oauth2client\crypt.py", line 97, in make_signed_jwt
    signature = signer.sign(signing_input)
AttributeError: 'str' object has no attribute 'sign'

**Comment by AmanKahlon90** [comment]
@torre76 I don't think so it has something to do with DGS coz I am not even importing that library, I am afraid that it has something to do with the apiclient library .

**Comment by torre76** [comment]
I think you are experiencing something like this: 

[PyOpenSSL missing implementation](https://github.com/google/oauth2client/issues/112)

But it is so strange, because the implementation is solved more than 3 years ago (and the Google client should have already solved this problem).

Try to include the new version of this library:

```bash
pip install pyOpenSSL
```

I am afraid I cannot help you so much on a project I do not know.

**Comment by AmanKahlon90** [comment]
@torre76 Tried pip install pyOpenSSL and it didnt get rid of that error. I am short of ideas.

**Comment by chengjaun** [comment]
Now I have the same error, did you end up resolving this issue?

**Comment by MrChadMWood** [comment]
Bump, I am receiving this error. 

https://support.google.com/googleplay/android-developer/answer/6135870
" Download reports using a client library and service account " > " See an example (Python) "

I assume this code is outdated. I attempted updating it to use `from oauth2client.service_account import ServiceAccountCredentials` which is how I got here.
