### ISSUE TITLE
ModuleNotFoundError: No module named 'gdstorageDefaults'

### ISSUE THREAD

**Issue by Softdude47** [torre76/django-googledrive-storage#48]
I keep getting *ModuleNotFoundError* when I try to make migration
```cmd
C:\Users\Godwin Precious\Desktop\ALL_PROG_FILE\PYTHON\TUTORIAL\WEB\BOOTCAMP_1>python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\Godwin Precious\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\Godwin Precious\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\management\__init__.py", line 377, in execute
    django.setup()
  File "C:\Users\Godwin Precious\AppData\Local\Programs\Python\Python37\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Godwin Precious\AppData\Local\Programs\Python\Python37\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\Godwin Precious\AppData\Local\Programs\Python\Python37\lib\site-packages\django\apps\config.py", line 90, in create
    module = import_module(entry)
  File "C:\Users\Godwin Precious\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'gdstorageDefaults'

C:\Users\Godwin Precious\Desktop\ALL_PROG_FILE\PYTHON\TUTORIAL\WEB\BOOTCAMP_1>python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\Godwin Precious\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\Godwin Precious\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\management\__init__.py", line 377, in execute
    django.setup()
  File "C:\Users\Godwin Precious\AppData\Local\Programs\Python\Python37\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Godwin Precious\AppData\Local\Programs\Python\Python37\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\Godwin Precious\AppData\Local\Programs\Python\Python37\lib\site-packages\django\apps\config.py", line 90, in create
    module = import_module(entry)
  File "C:\Users\Godwin Precious\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'gdstorageDefaults'
```

**Comment by torre76** [comment]
Hi @Softdude47,

it is not so simple to debug this error since gdstorage does not use defaults.
Could you send your settings.py so I can have an idea in what is going on?

**Comment by Softdude47** [comment]
I finally solved it
After fixing a *syntaxError* in the **INSTALLED_APPS** list, everything seems to work well

**Comment by torre76** [comment]
Thank you.

Now I can safely close this issue.
